# 2018학현초 아엠스쿨 주소록 정리

In [3]:
# 판다스 임포트 #pandas
import pandas as pd
from pandas import Series, DataFrame
import re

In [4]:
# 주소록 파일명
inputFile = 'pandas_hakAll.xlsx'

## 데이터 프레임 만들기(전체)

In [5]:
# 엑셀파일 불러서 데이터 프레임 만들기
df = pd.read_excel(inputFile)

# 2행부터 마지막 행까지 선택하기 loc[선택행, 선택열]
df = df.loc[2:,:]

# 인덱스 번호 재설정하기 
df.reset_index(drop=True, inplace=True)

# 칼럼 열 이름 재설정
df.columns = ['그룹','학년','반','학교이름','전화','메모']
df.head()

         그룹   학년    반      학교이름           전화   메모
0  2018발명센터  4학년  NaN    슬기초강시원  01027791100  NaN
1  2018발명센터  4학년  NaN    슬기초김세준  01034721713  NaN
2  2018발명센터  4학년  NaN    호동초김재영  01045031604  NaN
3  2018발명센터  4학년  NaN    반월초노은찬  01047822566  NaN
4  2018발명센터  4학년  NaN  안산청석초문성빈  01065120212  NaN

## #데이터 프레임 만들기

### 1. 데이터 프레임 : 전체

In [6]:
# 엑셀파일에서 원하는 열, 칼럼만 가져오기 헤더는 없음.
df1 = pd.read_excel(inputFile, usecols=[0,1, 3, 4], names=['그룹','학년','이름','전화'], header=None)
df1 = df1.loc[4:, :]
df1.reset_index(drop=True, inplace=True)
df1.head()

         그룹   학년        이름           전화
0  2018발명센터  4학년    슬기초강시원  01027791100
1  2018발명센터  4학년    슬기초김세준  01034721713
2  2018발명센터  4학년    호동초김재영  01045031604
3  2018발명센터  4학년    반월초노은찬  01047822566
4  2018발명센터  4학년  안산청석초문성빈  01065120212

### 2. 데이터 프레임 : 학부모

In [18]:
dfMother = df1.loc[54:675]
dfMother.head()

          그룹   학년   이름           전화
54  2018 학부모  1학년  강태루  01097929293
55  2018 학부모  1학년  강하준  01031679333
56  2018 학부모  1학년  구도현  01089743153
57  2018 학부모  1학년  김지후  01063221711
58  2018 학부모  1학년  박규민  01093727501

### 3. 데이터 프레임 : 교사

In [19]:
dfTeacher = df1.loc[461:507]
dfTeacher

           그룹  학년   이름           전화
461  2018 교직원  재직  김인숙  01027451126
462  2018 교직원  재직  안태우  01063367903
463  2018 교직원  재직  유정임  01092646832
464  2018 교직원  재직  김정혜  01049205072
465  2018 교직원  재직  이정화  01071516590
466  2018 교직원  재직  이민호  01089085957
467  2018 교직원  재직  이원님  01063972355
468  2018 교직원  재직  이보람  01025327105
469  2018 교직원  재직  김승희  01091386890
470  2018 교직원  재직  정나라  01086021378
471  2018 교직원  재직  김정연  01046911026
472  2018 교직원  재직  김성현  01026101478
473  2018 교직원  재직  류지영  01097763906
474  2018 교직원  재직  신혜영  01092514144
475  2018 교직원  재직  김소희  01094565665
476  2018 교직원  재직  신지원  01095085023
477  2018 교직원  재직  김홍란  01048258537
478  2018 교직원  재직  윤승희  01093045382
479  2018 교직원  재직  류창한  01087054073
480  2018 교직원  재직  우서경  01053934634
481  2018 교직원  재직  정은홍  01053599131
482  2018 교직원  재직  유수정  01074437236
483  2018 교직원  재직  최종철  01025489207
484  2018 교직원  재직  석진일  01027199719
485  2018 교직원  재직  이희두  01095767342
486  2018 교직원  재직  정현숙  01052665114
487  2018 교직원  재직  김문희  01034233045
488  2018 교직원  재직  남현화  01087665847
489  2018 교직원  재직  이다영  01091788907
490  2018 교직원  재직  박현경  01091427725
491  2018 교직원  재직  이미리  01045035216
492  2018 교직원  재직  최경란  01076670621
493  2018 교직원  재직  김제화  01039119278
494  2018 교직원  휴직  백미영  01051288755
495  2018 교직원  휴직  김수연  01020855961
496  2018 교직원  휴직  안도연  01029823083
497  2018 교직원  휴직  장은지  01020691682
498  2018 교직원  휴직  우승지  01083220393
499  2018 교직원  재직  박은정  01039052213
500  2018 교직원  재직  조일안  01090140573
501  2018 교직원  재직  박병한  01041469448
502  2018 교직원  재직  김을랑  01043082147
503  2018 교직원  재직  김문경  01050375246
504  2018 교직원  재직  박은실  01027723363
505  2018 교직원  재직  최영미  01025000212
506  2018 교직원  재직  김유정  01051645252
507  2018 교직원  재직  김미화  01039563509

### 4. 데이터 프레임 : 발명센터

In [22]:
dfInven = df1.loc[0:45]
dfInven

          그룹   학년        이름           전화
0   2018발명센터  4학년    슬기초강시원  01027791100
1   2018발명센터  4학년    슬기초김세준  01034721713
2   2018발명센터  4학년    호동초김재영  01045031604
3   2018발명센터  4학년    반월초노은찬  01047822566
4   2018발명센터  4학년  안산청석초문성빈  01065120212
5   2018발명센터  4학년  안산중앙초신효정  01083761772
6   2018발명센터  4학년    학현초이다현  01042962174
7   2018발명센터  4학년    학현초임수환  01051900082
8   2018발명센터  4학년    학현초전형규  01031247071
9   2018발명센터  4학년  안산해양초정진호  01054769947
10  2018발명센터  4학년  안산해양초조강현  01041574003
11  2018발명센터  4학년  안산부곡초주성운  01053594269
12  2018발명센터  5학년  안산호원초강주형  01043312542
13  2018발명센터  5학년    성포초구혜원  01089011272
14  2018발명센터  5학년    학현초김준영  01064847970
15  2018발명센터  5학년  안산청석초남시온  01048077818
16  2018발명센터  5학년    학현초박서진  01034233045
17  2018발명센터  5학년    성안초손형준  01073851026
18  2018발명센터  5학년    성포초신정민  01086650205
19  2018발명센터  5학년    슬기초양세비  01090888968
20  2018발명센터  5학년    성포초이선주  01020873277
21  2018발명센터  5학년    성포초장유찬  01090012588
22  2018발명센터  5학년    학현초전형찬  01031247071
23  2018발명센터  5학년    본원초최형찬  01025457452
24  2018발명센터  5학년  안산청석초함태민  01029111403
25  2018발명센터  6학년  안산진흥초권도형  01067348042
26  2018발명센터  6학년    상록초김강희  01056410105
27  2018발명센터  6학년  안산진흥초김규빈  01048170970
28  2018발명센터  6학년    학현초김소연  01041630528
29  2018발명센터  6학년    성안초김찬영  01030339782
30  2018발명센터  6학년    학현초민준기  01055029088
31  2018발명센터  6학년  안산진흥초박정민  01085453925
32  2018발명센터  6학년    학현초박준호  01056547576
33  2018발명센터  6학년    성안초백규현  01024382140
34  2018발명센터  6학년  안산중앙초신서희  01022899536
35  2018발명센터  6학년    학현초심동준  01091104765
36  2018발명센터  6학년    학현초오석준  01085798184
37  2018발명센터  6학년  안산진흥초오승민  01088517094
38  2018발명센터  6학년  안산진흥초원예슬  01064323122
39  2018발명센터  6학년  안산중앙초유도휘  01062282825
40  2018발명센터  6학년    상록초이서인  01033305105
41  2018발명센터  6학년  안산진흥초이주원  01087570925
42  2018발명센터  6학년  안산진흥초장선우  01063592282
43  2018발명센터  6학년    학현초전은율  01093752265
44  2018발명센터  6학년  안산진흥초홍수정  01053631786
45  2018발명센터  5학년    학현초서송연  01062345785

### 5. 데이터 프레임 : 발명센터 교사

In [28]:
dfInvenTeacher = df1.loc[46:53]
dfInvenTeacher

          그룹    학년   이름           전화
46  2018발명센터  지도교사  이정화  01071516590
47  2018발명센터  지도교사  김승희  01091386890
48  2018발명센터  지도교사  정나라  01086021378
49  2018발명센터  지도교사  류지영  01097763906
50  2018발명센터  지도교사  윤승희  01093045382
51  2018발명센터  지도교사  류창한  01087054073
52  2018발명센터  지도교사  석진일  01027199719
53  2018발명센터  지도교사  김한별  01025965907

## 그룹별로 정리하기

### #그룹 : 전체

In [32]:
groupByPart = df1.groupby('학년')
groupByPart.groups

{'1학년': Int64Index([ 54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
              67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
              80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
              93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
             106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 459, 530,
             573, 574, 650, 651, 652],
            dtype='int64'),
 '2분기 컴퓨터': Int64Index([575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587,
             588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600,
             601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613,
             614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626,
             627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639,
             640, 641, 642, 643, 644, 645, 646, 647, 648, 649],
            dtype='int64'),
 '2학년': Int64Index([117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
             130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
             143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
             156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
             169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
             182, 183, 184, 185, 186, 187, 188, 189],
            dtype='int64'),
 '3학년': Int64Index([190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
             203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
             216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
             229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
             242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253],
            dtype='int64'),
 '4학년': Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 254,
             255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
             268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
             281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
             294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306,
             307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
             320, 460],
            dtype='int64'),
 '5학년': Int64Index([ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
              45, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332,
             333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345,
             346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358,
             359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371,
             372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384,
             385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397,
             398, 399, 400, 572, 653],
            dtype='int64'),
 '6학년': Int64Index([ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
              38,  39,  40,  41,  42,  43,  44, 401, 402, 403, 404, 405, 406,
             407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419,
             420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432,
             433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445,
             446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458,
             557],
            dtype='int64'),
 '사물인터넷 특별반': Int64Index([544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556], dtype='int64'),
 '유치원': Int64Index([654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666,
             667, 668, 669, 670, 671, 672, 673, 674, 675],
            dtype='int64'),
 '인터넷드림단': Int64Index([531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543], dtype='int64'),
 '재직': Int64Index([461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473,
             474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486,
             487, 488, 489, 490, 491, 492, 493, 499, 500, 501, 502, 503, 504,
             505, 506, 507],
            dtype='int64'),
 '지도교사': Int64Index([46, 47, 48, 49, 50, 51, 52, 53], dtype='int64'),
 '학부모 코딩스쿨': Int64Index([558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570,
             571],
            dtype='int64'),
 '휴직': Int64Index([494, 495, 496, 497, 498], dtype='int64')}

In [33]:
for name, group in groupByPart:
        print(name + ':' + str(len(group)))
        print(group)
        print()

1학년:70
           그룹   학년     이름           전화
54   2018 학부모  1학년    강태루  01097929293
55   2018 학부모  1학년    강하준  01031679333
56   2018 학부모  1학년    구도현  01089743153
57   2018 학부모  1학년    김지후  01063221711
58   2018 학부모  1학년    박규민  01093727501
59   2018 학부모  1학년    박태환  01092048373
60   2018 학부모  1학년    박하진  01079270781
61   2018 학부모  1학년    백승윤  01024752800
62   2018 학부모  1학년    안현태  01083829349
63   2018 학부모  1학년    최태윤  01082211151
64   2018 학부모  1학년    김민서  01037296774
65   2018 학부모  1학년    김민채  01028702332
66   2018 학부모  1학년    김태희  01027545364
67   2018 학부모  1학년    김하랑  01042453794
68   2018 학부모  1학년    윤가람  01038738483
69   2018 학부모  1학년    이가연  01088972609
70   2018 학부모  1학년    이은솔  01042053515
71   2018 학부모  1학년    이지효  01044775077
72   2018 학부모  1학년    임하은  01024695678
73   2018 학부모  1학년    최시우  01083651727
74   2018 학부모  1학년    강열매  01058110509
75   2018 학부모  1학년    고정우  01027104060
76   2018 학부모  1학년    김하준  01076682157
77   2018 학부모  1학년    류서빈  01085075338
78   2018 학부모  1학년    박시욱  01038879254
79   2018 학부모  1학년    신동해  01024143320
80   2018 학부모  1학년    양시형  01030321015
81   2018 학부모  1학년    이영준  01047557597
82   2018 학부모  1학년    이 찬  01063293507
83   2018 학부모  1학년    이효준  01050421078
..        ...  ...    ...          ...
94   2018 학부모  1학년    이서빈  01032329795
95   2018 학부모  1학년    이소율  01054920703
96   2018 학부모  1학년    강정우  01094773008
97   2018 학부모  1학년    김용민  01086041324
98   2018 학부모  1학년    김태훈  01025961365
99   2018 학부모  1학년    노민준  01077384749
100  2018 학부모  1학년    안도현  01028210132
101  2018 학부모  1학년    왕지성  01024052201
102  2018 학부모  1학년    유강혁  01076678244
103  2018 학부모  1학년    전시환  01090074526
104  2018 학부모  1학년    조규빈  01090671703
105  2018 학부모  1학년    조채훈  01098642334
106  2018 학부모  1학년    최승현  01027535089
107  2018 학부모  1학년    고미랑  01056718099
108  2018 학부모  1학년    김서현  01044668694
109  2018 학부모  1학년    김시연  01047497613
110  2018 학부모  1학년    김아인  01093216927
111  2018 학부모  1학년    배서윤  01072837282
112  2018 학부모  1학년    유채하  01029791093
113  2018 학부모  1학년    유하정  01052430170
114  2018 학부모  1학년    이소율  01085256123
115  2018 학부모  1학년    임미훼  01072312666
116  2018 학부모  1학년    임아람  01034768625
459  2018 학부모  1학년    김가람  01023404255
530  2018 학부모  1학년    이예은  01066261792
573  2018 학부모  1학년    김진우  01052193229
574  2018 학부모  1학년    선시우  01027810082
650  2018 학부모  1학년  텐안젤리카  01057595969
651  2018 학부모  1학년   한진이스  01056690725
652  2018 학부모  1학년    한고샤  01056690725

[70 rows x 4 columns]

2분기 컴퓨터:75
          그룹       학년        이름           전화
575  방과후프로그램  2분기 컴퓨터   1-1 박태환  01092048373
576  방과후프로그램  2분기 컴퓨터   1-1 백승윤  01024752800
577  방과후프로그램  2분기 컴퓨터   1-1 이가연  01088972609
578  방과후프로그램  2분기 컴퓨터   1-1 이선준  01053190106
579  방과후프로그램  2분기 컴퓨터   1-2 김현지  01032965251
580  방과후프로그램  2분기 컴퓨터  1-2 이  찬  01063932379
581  방과후프로그램  2분기 컴퓨터   1-2 이효준  01050421078
582  방과후프로그램  2분기 컴퓨터   1-3 김용민  01086041324
583  방과후프로그램  2분기 컴퓨터   1-3 유채하  01036058699
584  방과후프로그램  2분기 컴퓨터   1-3 전시환  01090074526
585  방과후프로그램  2분기 컴퓨터   1-3 조규빈  01090671703
586  방과후프로그램  2분기 컴퓨터   1-3 최승현  01027535089
587  방과후프로그램  2분기 컴퓨터   2-1 배진원  01072837282
588  방과후프로그램  2분기 컴퓨터   2-2 국중현  01037109872
589  방과후프로그램  2분기 컴퓨터   2-2 양예서  01091272447
590  방과후프로그램  2분기 컴퓨터   2-2 유한결  01054461140
591  방과후프로그램  2분기 컴퓨터   2-3 오상훈  01090801400
592  방과후프로그램  2분기 컴퓨터   5-1 금준호  01051741260
593  방과후프로그램  2분기 컴퓨터   5-1 전성원  01091455760
594  방과후프로그램  2분기 컴퓨터   5-1 전형찬  01031247071
595  방과후프로그램  2분기 컴퓨터   5-1 김나은  01023096289
596  방과후프로그램  2분기 컴퓨터   5-1 박임윤  01032061553
597  방과후프로그램  2분기 컴퓨터   5-1 이소현  01088622315
598  방과후프로그램  2분기 컴퓨터   5-2 송건우  01041186394
599  방과후프로그램  2분기 컴퓨터   5-2 유민준  01054454498
600  방과후프로그램  2분기 컴퓨터   5-2 강민아  01027742347
601  방과후프로그램  2분기 컴퓨터   5-2 김주원  01085513370
602  방과후프로그램  2분기 컴퓨터   5-2 서송연  01062345785
603  방과후프로그램  2분기 컴퓨터   5-2 유미래  01027315197
604  방과후프로그램  2분기 컴퓨터   5-2 황효린  01042587745
..       ...      ...       ...          ...
620  방과후프로그램  2분기 컴퓨터   4-1 안태경  01092237962
621  방과후프로그램  2분기 컴퓨터   4-2 오태강  01047440342
622  방과후프로그램  2분기 컴퓨터   4-2 임채준  01056853523
623  방과후프로그램  2분기 컴퓨터   4-2 허승범  01096763461
624  방과후프로그램  2분기 컴퓨터   4-3 김강현  01048441999
625  방과후프로그램  2분기 컴퓨터   4-3 전형규  01031247071
626  방과후프로그램  2분기 컴퓨터   4-3 최재형  01041395839
627  방과후프로그램  2분기 컴퓨터   3-1 박시영  01090646647
628  방과후프로그램  2분기 컴퓨터   3-1 이성현  01050514682
629  방과후프로그램  2분기 컴퓨터  3-1 우  민  01090451570
630  방과후프로그램  2분기 컴퓨터   3-1 이지안  01044775077
631  방과후프로그램  2분기 컴퓨터   3-2 김예다  01033285511
632  방과후프로그램  2분기 컴퓨터   3-2 김예빈  01066056949
633  방과후프로그램  2분기 컴퓨터   3-2 김현아  01071122558
634  방과후프로그램  2분기 컴퓨터   3-2 김예슬  01066056949
635  방과후프로그램  2분기 컴퓨터   3-2 윤지은  01095801983
636  방과후프로그램  2분기 컴퓨터   3-3 김대윤  01033486015
637  방과후프로그램  2분기 컴퓨터   3-3 김재훈  01088218990
638  방과후프로그램  2분기 컴퓨터   3-3 정승호  01089218572
639  방과후프로그램  2분기 컴퓨터   4-1 박세윤  01086177035
640  방과후프로그램  2분기 컴퓨터   4-1 안예서  01029350455
641  방과후프로그램  2분기 컴퓨터   4-2 김민찬  01037421632
642  방과후프로그램  2분기 컴퓨터   4-2 진우림  01087216605
643  방과후프로그램  2분기 컴퓨터   4-2 김성경  01090422268
644  방과후프로그램  2분기 컴퓨터  4-2 우  현  01090451570
645  방과후프로그램  2분기 컴퓨터   4-2 이신영  01059202837
646  방과후프로그램  2분기 컴퓨터   4-3 고종학  01071082364
647  방과후프로그램  2분기 컴퓨터   4-3 신은혜  01024143320
648  방과후프로그램  2분기 컴퓨터   4-3 이다현  01042962174
649  방과후프로그램  2분기 컴퓨터   4-3 임현정  01033178117

[75 rows x 4 columns]

2학년:73
           그룹   학년   이름           전화
117  2018 학부모  2학년  김강한  01048441999
118  2018 학부모  2학년  김시후  01044736666
119  2018 학부모  2학년  김예준  01064625499
120  2018 학부모  2학년  김태정  01038915642
121  2018 학부모  2학년  김한결  01077771726
122  2018 학부모  2학년  남윤건  01049199279
123  2018 학부모  2학년  박정빈  01083920155
124  2018 학부모  2학년  배진원  01072837282
125  2018 학부모  2학년  이상윤  01026870426
126  2018 학부모  2학년  이진호  01087293527
127  2018 학부모  2학년  조민상  01037749041
128  2018 학부모  2학년  최희찬  01086148868
129  2018 학부모  2학년  황유건  01042587745
130  2018 학부모  2학년  황지우  01076211786
131  2018 학부모  2학년  권혜인  01085932541
132  2018 학부모  2학년  김가을  01089308277
133  2018 학부모  2학년  김지우  01062079299
134  2018 학부모  2학년  김효빈  01087181730
135  2018 학부모  2학년  서여원  01089955411
136  2018 학부모  2학년  송혜민  01098503035
137  2018 학부모  2학년  이지영  01031523406
138  2018 학부모  2학년  정다은  01024418528
139  2018 학부모  2학년  진채율  01033281327
140  2018 학부모  2학년  최재희  01041395839
141  2018 학부모  2학년  최하람  01063549519
142  2018 학부모  2학년  최희서  01033698183
143  2018 학부모  2학년  국중현  01037109872
144  2018 학부모  2학년  김도언  01074912007
145  2018 학부모  2학년  김호언  01026363878
146  2018 학부모  2학년  박준형  01090646647
..        ...  ...  ...          ...
160  2018 학부모  2학년  박희서  01040174132
161  2018 학부모  2학년  손민영  01090466254
162  2018 학부모  2학년  심혜령  01026151991
163  2018 학부모  2학년  양예서  01091272447
164  2018 학부모  2학년  위다희  01076591018
165  2018 학부모  2학년  정유비  01083982050
166  2018 학부모  2학년  정지우  01090540337
167  2018 학부모  2학년  김한결  01083778578
168  2018 학부모  2학년  노하선  01024072315
169  2018 학부모  2학년  박서우  01035538344
170  2018 학부모  2학년  박준서  01095102208
171  2018 학부모  2학년  박준우  01095102208
172  2018 학부모  2학년  송하율  01027407033
173  2018 학부모  2학년  양태준  01047823627
174  2018 학부모  2학년  이시우  01051780427
175  2018 학부모  2학년  장준혁  01075536032
176  2018 학부모  2학년   조권  01086461404
177  2018 학부모  2학년  황도원  01032288251
178  2018 학부모  2학년  권예본  01027604325
179  2018 학부모  2학년  김지우  01098838772
180  2018 학부모  2학년  김채윤  01088192006
181  2018 학부모  2학년  문성윤  01040500393
182  2018 학부모  2학년  송하은  01023363152
183  2018 학부모  2학년  신현진  01036266166
184  2018 학부모  2학년  이다온  01024818447
185  2018 학부모  2학년  이루리  01087911795
186  2018 학부모  2학년  이주현  01082465533
187  2018 학부모  2학년  장하영  01087450785
188  2018 학부모  2학년  정수미  01057195222
189  2018 학부모  2학년  홍지은  01043678522

[73 rows x 4 columns]

3학년:64
           그룹   학년    이름           전화
190  2018 학부모  3학년   권준혁  01046081339
191  2018 학부모  3학년   김민규  01089185235
192  2018 학부모  3학년   김범진  01088060423
193  2018 학부모  3학년   김용찬  01026663271
194  2018 학부모  3학년   박성환  01088282131
195  2018 학부모  3학년   박시영  01090646647
196  2018 학부모  3학년   박시훈  01093727501
197  2018 학부모  3학년   안도현  01087092917
198  2018 학부모  3학년   오윤성  01047663085
199  2018 학부모  3학년   왕지후  01024052201
200  2018 학부모  3학년   이성현  01050514682
201  2018 학부모  3학년   이원준  01035191425
202  2018 학부모  3학년   채준서  01062610726
203  2018 학부모  3학년  김밀라나  01091893356
204  2018 학부모  3학년   김수아  01085513370
205  2018 학부모  3학년   김시향  01044736666
206  2018 학부모  3학년   김지율  01091779142
207  2018 학부모  3학년   박상윤  01092048373
208  2018 학부모  3학년    우민  01090451570
209  2018 학부모  3학년   이지안  01044775077
210  2018 학부모  3학년   임가은  01024695678
211  2018 학부모  3학년   추서윤  01023407284
212  2018 학부모  3학년   김민준  01033226185
213  2018 학부모  3학년   김지훈  01097474310
214  2018 학부모  3학년   양재현  01079632504
215  2018 학부모  3학년   오승민  01024421377
216  2018 학부모  3학년   유강연  01047074084
217  2018 학부모  3학년   이건희  01042053515
218  2018 학부모  3학년    이원  01032144455
219  2018 학부모  3학년   이재혁  01084430626
..        ...  ...   ...          ...
224  2018 학부모  3학년   김예다  01033285511
225  2018 학부모  3학년   김예빈  01066056949
226  2018 학부모  3학년   김예슬  01066056949
227  2018 학부모  3학년   김현아  01071122558
228  2018 학부모  3학년   양하진  01024392570
229  2018 학부모  3학년   윤지은  01095801983
230  2018 학부모  3학년   허민지  01090831279
231  2018 학부모  3학년   김대윤  01033486015
232  2018 학부모  3학년   김민식  01041630528
233  2018 학부모  3학년   김재훈  01088218990
234  2018 학부모  3학년   민은기  01055029088
235  2018 학부모  3학년   박현후  01090747944
236  2018 학부모  3학년   손수창  01055806891
237  2018 학부모  3학년   이동훈  01088622315
238  2018 학부모  3학년   이상훈  01033080152
239  2018 학부모  3학년   장윤성  01089439377
240  2018 학부모  3학년   정승열  01062118540
241  2018 학부모  3학년   정승호  01089218572
242  2018 학부모  3학년   정인하  01039318474
243  2018 학부모  3학년   강민지  01027742347
244  2018 학부모  3학년   강영글  01058110509
245  2018 학부모  3학년   고미송  01056718099
246  2018 학부모  3학년   박보영  01026276165
247  2018 학부모  3학년   안령선  01079398931
248  2018 학부모  3학년   윤서하  01028261630
249  2018 학부모  3학년   장예은  01085353350
250  2018 학부모  3학년   장혜주  01089439377
251  2018 학부모  3학년   정아린  01052954365
252  2018 학부모  3학년   조민진  01086007971
253  2018 학부모  3학년   주다인  01042893333

[64 rows x 4 columns]

4학년:80
           그룹   학년        이름           전화
0    2018발명센터  4학년    슬기초강시원  01027791100
1    2018발명센터  4학년    슬기초김세준  01034721713
2    2018발명센터  4학년    호동초김재영  01045031604
3    2018발명센터  4학년    반월초노은찬  01047822566
4    2018발명센터  4학년  안산청석초문성빈  01065120212
5    2018발명센터  4학년  안산중앙초신효정  01083761772
6    2018발명센터  4학년    학현초이다현  01042962174
7    2018발명센터  4학년    학현초임수환  01051900082
8    2018발명센터  4학년    학현초전형규  01031247071
9    2018발명센터  4학년  안산해양초정진호  01054769947
10   2018발명센터  4학년  안산해양초조강현  01041574003
11   2018발명센터  4학년  안산부곡초주성운  01053594269
254  2018 학부모  4학년       김동규  01020739888
255  2018 학부모  4학년       김민찬  01037421632
256  2018 학부모  4학년       김시우  01047497613
257  2018 학부모  4학년       김태건  01075944111
258  2018 학부모  4학년       서무빈  01088348534
259  2018 학부모  4학년       안태경  01092237962
260  2018 학부모  4학년       이성진  01029571751
261  2018 학부모  4학년       이현진  01082465533
262  2018 학부모  4학년       임수환  01051900082
263  2018 학부모  4학년       장영진  01086035260
264  2018 학부모  4학년       조한결  01040653308
265  2018 학부모  4학년       최태현  01082211151
266  2018 학부모  4학년       고미강  01056718099
267  2018 학부모  4학년       김세린  01022451633
268  2018 학부모  4학년       김수현  01098342427
269  2018 학부모  4학년       박세윤  01086177035
270  2018 학부모  4학년       서연우  01089955411
271  2018 학부모  4학년       심나령  01026151991
..        ...  ...       ...          ...
292  2018 학부모  4학년       김성경  01090422268
293  2018 학부모  4학년       박지혜  01033989969
294  2018 학부모  4학년       박희재  01040174132
295  2018 학부모  4학년       방소희  01089984889
296  2018 학부모  4학년       오승현  01028530317
297  2018 학부모  4학년        우현  01090451570
298  2018 학부모  4학년       유지현  01052430170
299  2018 학부모  4학년       이시연  01087911795
300  2018 학부모  4학년       이신영  01059202837
301  2018 학부모  4학년       장민영  01087450785
302  2018 학부모  4학년       황정원  01028293346
303  2018 학부모  4학년       고종학  01071082364
304  2018 학부모  4학년       김강현  01048441999
305  2018 학부모  4학년       김채원  01033640709
306  2018 학부모  4학년       박상진  01056872921
307  2018 학부모  4학년       양병철  01046911026
308  2018 학부모  4학년       양태현  01047823627
309  2018 학부모  4학년       정원우  01057497718
310  2018 학부모  4학년       최재형  01041395839
311  2018 학부모  4학년       고은달  01049969355
312  2018 학부모  4학년       김시연  01063355450
313  2018 학부모  4학년       신은혜  01024143320
314  2018 학부모  4학년       이다현  01042962174
315  2018 학부모  4학년       이윤선  01084722188
316  2018 학부모  4학년       이지우  01090211510
317  2018 학부모  4학년       이해인  01084498141
318  2018 학부모  4학년       임현정  01033178117
319  2018 학부모  4학년       조하연  01049483221
320  2018 학부모  4학년       최경화  01033315446
460  2018 학부모  4학년       김아름  01023404255

[80 rows x 4 columns]

5학년:96
           그룹   학년        이름           전화
12   2018발명센터  5학년  안산호원초강주형  01043312542
13   2018발명센터  5학년    성포초구혜원  01089011272
14   2018발명센터  5학년    학현초김준영  01064847970
15   2018발명센터  5학년  안산청석초남시온  01048077818
16   2018발명센터  5학년    학현초박서진  01034233045
17   2018발명센터  5학년    성안초손형준  01073851026
18   2018발명센터  5학년    성포초신정민  01086650205
19   2018발명센터  5학년    슬기초양세비  01090888968
20   2018발명센터  5학년    성포초이선주  01020873277
21   2018발명센터  5학년    성포초장유찬  01090012588
22   2018발명센터  5학년    학현초전형찬  01031247071
23   2018발명센터  5학년    본원초최형찬  01025457452
24   2018발명센터  5학년  안산청석초함태민  01029111403
45   2018발명센터  5학년    학현초서송연  01062345785
321  2018 학부모  5학년       고판준  01056718099
322  2018 학부모  5학년       금준호  01051741260
323  2018 학부모  5학년       김범찬  01094707702
324  2018 학부모  5학년       김승우  01087181730
325  2018 학부모  5학년       김준영  01064847970
326  2018 학부모  5학년       박서진  01034233045
327  2018 학부모  5학년       박태건  01093748294
328  2018 학부모  5학년       이승주  01053057534
329  2018 학부모  5학년       이정우  01095052509
330  2018 학부모  5학년       임지훈  01024219045
331  2018 학부모  5학년       전성원  01091455760
332  2018 학부모  5학년       탁광용  01088999728
333  2018 학부모  5학년       김나은  01023096289
334  2018 학부모  5학년       김주연  01084835768
335  2018 학부모  5학년       김지우  01056369008
336  2018 학부모  5학년       김휘겸  01088838534
..        ...  ...       ...          ...
373  2018 학부모  5학년  고빅또리아에밀리  01049969355
374  2018 학부모  5학년       김동준  01036268927
375  2018 학부모  5학년       김소우  01023245558
376  2018 학부모  5학년       김한울  01091779142
377  2018 학부모  5학년       남윤찬  01049199279
378  2018 학부모  5학년       문정완  01040500393
379  2018 학부모  5학년       박상현  01027517335
380  2018 학부모  5학년       박현빈  01090747944
381  2018 학부모  5학년        사타  01059609939
382  2018 학부모  5학년       이은상  01030887494
383  2018 학부모  5학년       정범수  01089218572
384  2018 학부모  5학년        정윤  01094444665
385  2018 학부모  5학년       정태주  01082304422
386  2018 학부모  5학년       하윤찬  01092951961
387  2018 학부모  5학년       고나윤  01051279992
388  2018 학부모  5학년       김슬아  01053205493
389  2018 학부모  5학년       성예원  01031265630
390  2018 학부모  5학년       송지우  01051237724
391  2018 학부모  5학년       신채현  01076671682
392  2018 학부모  5학년       양연실  01022292317
393  2018 학부모  5학년       양하은  01024392570
394  2018 학부모  5학년       오혜린  01028530317
395  2018 학부모  5학년       이시아  01092695588
396  2018 학부모  5학년       정세은  01039318474
397  2018 학부모  5학년       정연지  01045410914
398  2018 학부모  5학년       주해인  01042893333
399  2018 학부모  5학년       최나라  01088764581
400  2018 학부모  5학년       최유림  01074555884
572  2018 학부모  5학년       조연주  01084945421
653  2018 학부모  5학년       이채빈  01022977628

[96 rows x 4 columns]

6학년:79
           그룹   학년        이름           전화
25   2018발명센터  6학년  안산진흥초권도형  01067348042
26   2018발명센터  6학년    상록초김강희  01056410105
27   2018발명센터  6학년  안산진흥초김규빈  01048170970
28   2018발명센터  6학년    학현초김소연  01041630528
29   2018발명센터  6학년    성안초김찬영  01030339782
30   2018발명센터  6학년    학현초민준기  01055029088
31   2018발명센터  6학년  안산진흥초박정민  01085453925
32   2018발명센터  6학년    학현초박준호  01056547576
33   2018발명센터  6학년    성안초백규현  01024382140
34   2018발명센터  6학년  안산중앙초신서희  01022899536
35   2018발명센터  6학년    학현초심동준  01091104765
36   2018발명센터  6학년    학현초오석준  01085798184
37   2018발명센터  6학년  안산진흥초오승민  01088517094
38   2018발명센터  6학년  안산진흥초원예슬  01064323122
39   2018발명센터  6학년  안산중앙초유도휘  01062282825
40   2018발명센터  6학년    상록초이서인  01033305105
41   2018발명센터  6학년  안산진흥초이주원  01087570925
42   2018발명센터  6학년  안산진흥초장선우  01063592282
43   2018발명센터  6학년    학현초전은율  01093752265
44   2018발명센터  6학년  안산진흥초홍수정  01053631786
401  2018 학부모  6학년       고병욱  01027101416
402  2018 학부모  6학년       김정민  01090717450
403  2018 학부모  6학년       민준기  01055029088
404  2018 학부모  6학년       박종석  01072557212
405  2018 학부모  6학년       박준호  01056547576
406  2018 학부모  6학년       윤태현  01077077880
407  2018 학부모  6학년       정민용  01032276776
408  2018 학부모  6학년       진선웅  01096313329
409  2018 학부모  6학년       홍은택  01043678522
410  2018 학부모  6학년       곽가영  01066470964
..        ...  ...       ...          ...
430  2018 학부모  6학년       김지우  01041519110
431  2018 학부모  6학년       김혜인  01087830000
432  2018 학부모  6학년       손정원  01034414692
433  2018 학부모  6학년       오유진  01047440342
434  2018 학부모  6학년       윤서원  01095557052
435  2018 학부모  6학년       이성린  01050514682
436  2018 학부모  6학년       이혜인  01023939945
437  2018 학부모  6학년       정민서  01062118540
438  2018 학부모  6학년       황주원  01079791516
439  2018 학부모  6학년       김민균  01050072173
440  2018 학부모  6학년       김민재  01098543358
441  2018 학부모  6학년       박태완  01049501219
442  2018 학부모  6학년       오석준  01085798184
443  2018 학부모  6학년       오현우  01084651467
444  2018 학부모  6학년       유승연  01047074084
445  2018 학부모  6학년       이시영  01089460472
446  2018 학부모  6학년       이호준  01043037472
447  2018 학부모  6학년       전은율  01093752265
448  2018 학부모  6학년       김용하  01021115895
449  2018 학부모  6학년       김가람  01026663271
450  2018 학부모  6학년       김가은  01062011632
451  2018 학부모  6학년       김민서  01067741173
452  2018 학부모  6학년       김보경  01071443161
453  2018 학부모  6학년       안윤서  01028210132
454  2018 학부모  6학년       윤재인  01099372002
455  2018 학부모  6학년       이서인  01084498141
456  2018 학부모  6학년       이예진  01071217758
457  2018 학부모  6학년       장혜윤  01041538765
458  2018 학부모  6학년       채연서  01062610726
557  2018 학부모  6학년       홍석우  01067226550

[79 rows x 4 columns]

사물인터넷 특별반:13
           그룹         학년   이름           전화
544  2018발명센터  사물인터넷 특별반  권예성  01027604325
545  2018발명센터  사물인터넷 특별반  김소연  01041630528
546  2018발명센터  사물인터넷 특별반  김용하  01021115895
547  2018발명센터  사물인터넷 특별반  박서진  01034233045
548  2018발명센터  사물인터넷 특별반  심동준  01091104765
549  2018발명센터  사물인터넷 특별반  양건호  01091272447
550  2018발명센터  사물인터넷 특별반  양하은  01024392570
551  2018발명센터  사물인터넷 특별반  이서인  01053945105
552  2018발명센터  사물인터넷 특별반  이해인  01087755105
553  2018발명센터  사물인터넷 특별반  전은율  01093752265
554  2018발명센터  사물인터넷 특별반  정민용  01091298187
555  2018발명센터  사물인터넷 특별반  최나라  01088764581
556  2018발명센터  사물인터넷 특별반  황현우  01076211786

유치원:22
           그룹   학년   이름           전화
654  2018 학부모  유치원  서지유  01062345785
655  2018 학부모  유치원  박하윤  01032061553
656  2018 학부모  유치원  임현진  01033178117
657  2018 학부모  유치원  유민하  01036058699
658  2018 학부모  유치원  남윤채  01049199279
659  2018 학부모  유치원  김연우  01062079299
660  2018 학부모  유치원  김지윤  01088192006
661  2018 학부모  유치원  이소윤  01088062325
662  2018 학부모  유치원  이채민  01031523406
663  2018 학부모  유치원  최윤채  01062650718
664  2018 학부모  유치원  김서준  01025853476
665  2018 학부모  유치원  이민혁  01088678306
666  2018 학부모  유치원  김영광  01039067363
667  2018 학부모  유치원  강라온  01088126047
668  2018 학부모  유치원  김은조  01045244228
669  2018 학부모  유치원  위다현  01076591018
670  2018 학부모  유치원  구나연  01089743153
671  2018 학부모  유치원  윤성재  01096723625
672  2018 학부모  유치원  고준서  01056718099
673  2018 학부모  유치원  조연우  01066812711
674  2018 학부모  유치원  우승준  01063505401
675  2018 학부모  유치원  이재희  01084430626

인터넷드림단:13
           그룹      학년   이름           전화
531  2018발명센터  인터넷드림단  김채원  01033640709
532  2018발명센터  인터넷드림단  임현정  01033178117
533  2018발명센터  인터넷드림단  한효림  01039540219
534  2018발명센터  인터넷드림단  이주경  01026197512
535  2018발명센터  인터넷드림단  김민주  01088060423
536  2018발명센터  인터넷드림단  류승화  01085075338
537  2018발명센터  인터넷드림단  양하은  01024392570
538  2018발명센터  인터넷드림단  이시아  01092695588
539  2018발명센터  인터넷드림단  최나라  01088764581
540  2018발명센터  인터넷드림단  임희수  01051900082
541  2018발명센터  인터넷드림단  김윤서  01087841357
542  2018발명센터  인터넷드림단  채연서  01062610726
543  2018발명센터  인터넷드림단  안예서  01029350455

재직:42
           그룹  학년   이름           전화

### #그룹 : 학년별

In [31]:
groupByGrade = dfMother.groupby('학년')
groupByGrade.groups

{'1학년': Int64Index([ 54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
              67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
              80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
              93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
             106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 459, 530,
             573, 574, 650, 651, 652],
            dtype='int64'),
 '2분기 컴퓨터': Int64Index([575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587,
             588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600,
             601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613,
             614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626,
             627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639,
             640, 641, 642, 643, 644, 645, 646, 647, 648, 649],
            dtype='int64'),
 '2학년': Int64Index([117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
             130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
             143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
             156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
             169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
             182, 183, 184, 185, 186, 187, 188, 189],
            dtype='int64'),
 '3학년': Int64Index([190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
             203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
             216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
             229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
             242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253],
            dtype='int64'),
 '4학년': Int64Index([254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266,
             267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279,
             280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292,
             293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305,
             306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318,
             319, 320, 460],
            dtype='int64'),
 '5학년': Int64Index([321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333,
             334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346,
             347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359,
             360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372,
             373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385,
             386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398,
             399, 400, 572, 653],
            dtype='int64'),
 '6학년': Int64Index([401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
             414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
             427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
             440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452,
             453, 454, 455, 456, 457, 458, 557],
            dtype='int64'),
 '사물인터넷 특별반': Int64Index([544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556], dtype='int64'),
 '유치원': Int64Index([654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666,
             667, 668, 669, 670, 671, 672, 673, 674, 675],
            dtype='int64'),
 '인터넷드림단': Int64Index([531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543], dtype='int64'),
 '재직': Int64Index([461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473,
             474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486,
             487, 488, 489, 490, 491, 492, 493, 499, 500, 501, 502, 503, 504,
             505, 506, 507],
            dtype='int64'),
 '학부모 코딩스쿨': Int64Index([558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570,
             571],
            dtype='int64'),
 '휴직': Int64Index([494, 495, 496, 497, 498], dtype='int64')}

In [9]:
for name, group in groupByGrade:
        print(name + ':' + str(len(group)))
        print(group)
        print()

2018 각종연수:14
            그룹        학년   이름           전화
558  2018 각종연수  학부모 코딩스쿨  안은실  01022899536
559  2018 각종연수  학부모 코딩스쿨  전순화  01087216605
560  2018 각종연수  학부모 코딩스쿨  최혜진  01055029088
561  2018 각종연수  학부모 코딩스쿨  김기숙  01024392570
562  2018 각종연수  학부모 코딩스쿨  설혜선  01076211786
563  2018 각종연수  학부모 코딩스쿨  황은경  01088060423
564  2018 각종연수  학부모 코딩스쿨  변혜정  01040500393
565  2018 각종연수  학부모 코딩스쿨  유현주  01050613165
566  2018 각종연수  학부모 코딩스쿨  강윤성  01032276776
567  2018 각종연수  학부모 코딩스쿨  나자은  01085353350
568  2018 각종연수  학부모 코딩스쿨  전순화  01087216605
569  2018 각종연수  학부모 코딩스쿨  배현미  01093748294
570  2018 각종연수  학부모 코딩스쿨  김진희  01094707702
571  2018 각종연수  학부모 코딩스쿨  이경선  01037421632

2018 교직원:47
           그룹  학년   이름           전화
461  2018 교직원  재직  김인숙  01027451126
462  2018 교직원  재직  안태우  01063367903
463  2018 교직원  재직  유정임  01092646832
464  2018 교직원  재직  김정혜  01049205072
465  2018 교직원  재직  이정화  01071516590
466  2018 교직원  재직  이민호  01089085957
467  2018 교직원  재직  이원님  01063972355
468  2018 교직원  재직  이보람  01025327105
469  2018 교직원  재직  김승희  01091386890
470  2018 교직원  재직  정나라  01086021378
471  2018 교직원  재직  김정연  01046911026
472  2018 교직원  재직  김성현  01026101478
473  2018 교직원  재직  류지영  01097763906
474  2018 교직원  재직  신혜영  01092514144
475  2018 교직원  재직  김소희  01094565665
476  2018 교직원  재직  신지원  01095085023
477  2018 교직원  재직  김홍란  01048258537
478  2018 교직원  재직  윤승희  01093045382
479  2018 교직원  재직  류창한  01087054073
480  2018 교직원  재직  우서경  01053934634
481  2018 교직원  재직  정은홍  01053599131
482  2018 교직원  재직  유수정  01074437236
483  2018 교직원  재직  최종철  01025489207
484  2018 교직원  재직  석진일  01027199719
485  2018 교직원  재직  이희두  01095767342
486  2018 교직원  재직  정현숙  01052665114
487  2018 교직원  재직  김문희  01034233045
488  2018 교직원  재직  남현화  01087665847
489  2018 교직원  재직  이다영  01091788907
490  2018 교직원  재직  박현경  01091427725
491  2018 교직원  재직  이미리  01045035216
492  2018 교직원  재직  최경란  01076670621
493  2018 교직원  재직  김제화  01039119278
494  2018 교직원  휴직  백미영  01051288755
495  2018 교직원  휴직  김수연  01020855961
496  2018 교직원  휴직  안도연  01029823083
497  2018 교직원  휴직  장은지  01020691682
498  2018 교직원  휴직  우승지  01083220393
499  2018 교직원  재직  박은정  01039052213
500  2018 교직원  재직  조일안  01090140573
501  2018 교직원  재직  박병한  01041469448
502  2018 교직원  재직  김을랑  01043082147
503  2018 교직원  재직  김문경  01050375246
504  2018 교직원  재직  박은실  01027723363
505  2018 교직원  재직  최영미  01025000212
506  2018 교직원  재직  김유정  01051645252
507  2018 교직원  재직  김미화  01039563509

2018 학부모:438
           그룹   학년     이름           전화
54   2018 학부모  1학년    강태루  01097929293
55   2018 학부모  1학년    강하준  01031679333
56   2018 학부모  1학년    구도현  01089743153
57   2018 학부모  1학년    김지후  01063221711
58   2018 학부모  1학년    박규민  01093727501
59   2018 학부모  1학년    박태환  01092048373
60   2018 학부모  1학년    박하진  01079270781
61   2018 학부모  1학년    백승윤  01024752800
62   2018 학부모  1학년    안현태  01083829349
63   2018 학부모  1학년    최태윤  01082211151
64   2018 학부모  1학년    김민서  01037296774
65   2018 학부모  1학년    김민채  01028702332
66   2018 학부모  1학년    김태희  01027545364
67   2018 학부모  1학년    김하랑  01042453794
68   2018 학부모  1학년    윤가람  01038738483
69   2018 학부모  1학년    이가연  01088972609
70   2018 학부모  1학년    이은솔  01042053515
71   2018 학부모  1학년    이지효  01044775077
72   2018 학부모  1학년    임하은  01024695678
73   2018 학부모  1학년    최시우  01083651727
74   2018 학부모  1학년    강열매  01058110509
75   2018 학부모  1학년    고정우  01027104060
76   2018 학부모  1학년    김하준  01076682157
77   2018 학부모  1학년    류서빈  01085075338
78   2018 학부모  1학년    박시욱  01038879254
79   2018 학부모  1학년    신동해  01024143320
80   2018 학부모  1학년    양시형  01030321015
81   2018 학부모  1학년    이영준  01047557597
82   2018 학부모  1학년    이 찬  01063293507
83   2018 학부모  1학년    이효준  01050421078
..        ...  ...    ...          ...
557  2018 학부모  6학년    홍석우  01067226550
572  2018 학부모  5학년    조연주  01084945421
573  2018 학부모  1학년    김진우  01052193229
574  2018 학부모  1학년    선시우  01027810082
650  2018 학부모  1학년  텐안젤리카  01057595969
651  2018 학부모  1학년   한진이스  01056690725
652  2018 학부모  1학년    한고샤  01056690725
653  2018 학부모  5학년    이채빈  01022977628
654  2018 학부모  유치원    서지유  01062345785
655  2018 학부모  유치원    박하윤  01032061553
656  2018 학부모  유치원    임현진  01033178117
657  2018 학부모  유치원    유민하  01036058699
658  2018 학부모  유치원    남윤채  01049199279
659  2018 학부모  유치원    김연우  01062079299
660  2018 학부모  유치원    김지윤  01088192006
661  2018 학부모  유치원    이소윤  01088062325
662  2018 학부모  유치원    이채민  01031523406
663  2018 학부모  유치원    최윤채  01062650718
664  2018 학부모  유치원    김서준  01025853476
665  2018 학부모  유치원    이민혁  01088678306
666  2018 학부모  유치원    김영광  01039067363
667  2018 학부모  유치원    강라온  01088126047
668  2018 학부모  유치원    김은조  01045244228
669  2018 학부모  유치원    위다현  01076591018
670  2018 학부모  유치원    구나연  01089743153
671  2018 학부모  유치원    윤성재  01096723625
672  2018 학부모  유치원    고준서  01056718099
673  2018 학부모  유치원    조연우  01066812711
674  2018 학부모  유치원    우승준  01063505401
675  2018 학부모  유치원    이재희  01084430626

[438 rows x 4 columns]

2018 학운위 :7
            그룹   학년   이름           전화
523  2018 학운위   NaN  금재성  01029342938
524  2018 학운위   NaN  김소영  01090717450
525  2018 학운위   NaN  박미경  01084925007
526  2018 학운위   NaN  임경희  01042453794
527  2018 학운위   NaN  황은경  01088060423
528  2018 학운위   NaN  박영순  01088192006
529  2018 학운위   NaN  강신우  01076692771

2018발명센터:80
           그룹         학년        이름           전화
0    2018발명센터        4학년    슬기초강시원  01027791100
1    2018발명센터        4학년    슬기초김세준  01034721713
2    2018발명센터        4학년    호동초김재영  01045031604
3    2018발명센터        4학년    반월초노은찬  01047822566
4    2018발명센터        4학년  안산청석초문성빈  01065120212
5    2018발명센터        4학년  안산중앙초신효정  01083761772
6    2018발명센터        4학년    학현초이다현  01042962174
7    2018발명센터        4학년    학현초임수환  01051900082
8    2018발명센터        4학년    학현초전형규  01031247071
9    2018발명센터        4학년  안산해양초정진호  01054769947
10   2018발명센터        4학년  안산해양초조강현  01041574003
11   2018발명센터        4학년  안산부곡초주성운  01053594269
12   2018발명센터        5학년  안산호원초강주형  01043312542
13   2018발명센터        5학년    성포초구혜원  01089011272
14   2018발명센터        5학년    학현초김준영  01064847970
15   2018발명센터        5학년  안산청석초남시온  01048077818
16   2018발명센터        5학년    학현초박서진  01034233045
17   2018발명센터        5학년    성안초손형준  01073851026
18   2018발명센터        5학년    성포초신정민  01086650205
19   2018발명센터        5학년    슬기초양세비  01090888968
20   2018발명센터        5학년    성포초이선주  01020873277
21   2018발명센터        5학년    성포초장유찬  01090012588
22   2018발명센터        5학년    학현초전형찬  01031247071
23   2018발명센터        5학년    본원초최형찬  01025457452
24   2018발명센터        5학년  안산청석초함태민  01029111403
25   2018발명센터        6학년  안산진흥초권도형  01067348042
26   2018발명센터        6학년    상록초김강희  01056410105
27   2018발명센터        6학년  안산진흥초김규빈  01048170970
28   2018발명센터        6학년    학현초김소연  01041630528
29   2018발명센터        6학년    성안초김찬영  01030339782
..        ...        ...       ...          ...
50   2018발명센터       지도교사       윤승희  01093045382
51   2018발명센터       지도교사       류창한  01087054073
52   2018발명센터       지도교사       석진일  01027199719
53   2018발명센터       지도교사       김한별  01025965907
531  2018발명센터     인터넷드림단       김채원  01033640709
532  2018발명센터     인터넷드림단       임현정  01033178117
533  2018발명센터     인터넷드림단       한효림  01039540219
534  2018발명센터     인터넷드림단       이주경  01026197512
535  2018발명센터     인터넷드림단       김민주  01088060423
536  2018발명센터     인터넷드림단       류승화  01085075338
537  2018발명센터     인터넷드림단       양하은  01024392570
538  2018발명센터     인터넷드림단       이시아  01092695588
539  2018발명센터     인터넷드림단       최나라  01088764581
540  2018발명센터     인터넷드림단       임희수  01051900082
541  2018발명센터     인터넷드림단       김윤서  01087841357
542  2018발명센터     인터넷드림단       채연서  01062610726
543  2018발명센터     인터넷드림단       안예서  01029350455
544  2018발명센터  사물인터넷 특별반       권예성  01027604325
545  2018발명센터  사물인터넷 특별반       김소연  01041630528
546  2018발명센터  사물인터넷 특별반       김용하  01021115895
547  2018발명센터  사물인터넷 특별반       박서진  01034233045
548  2018발명센터  사물인터넷 특별반       심동준  01091104765
549  2018발명센터  사물인터넷 특별반       양건호  01091272447
550  2018발명센터  사물인터넷 특별반       양하은  01024392570
551  2018발명센터  사물인터넷 특별반       이서인  01053945105
552  2018발명센터  사물인터넷 특별반       이해인  01087755105
553  2018발명센터  사물인터넷 특별반       전은율  01093752265
554  2018발명센터  사물인터넷 특별반       정민용  01091298187
555  2018발명센터  사물인터넷 특별반       최나라  01088764581
556  2018발명센터  사물인터넷 특별반       황현우  01076211786

[80 rows x 4 columns]

2018방과후강사:15
            그룹   학년   이름           전화
508  2018방과후강사  NaN  박경원  01040099705
509  2018방과후강사  NaN  이정미  01033671203
510  2018방과후강사  NaN  김소라  01022682657
511  2018방과후강사  NaN  장유민  01071969268
512  2018방과후강사  NaN  우성혜  01027244978
513  2018방과후강사  NaN  유영미  01088036269
514  2018방과후강사  NaN  석경은  01033223104
515  2018방과후강사  NaN  신선주  01074210412
516  2018방과후강사  NaN  정혜선  01088140619
517  2018방과후강사  NaN  한미란  01024949597
518  2018방과후강사  NaN  신수연  01028241365
519  2018방과후강사  NaN  유현정  01091323686
520  2018방과후강사  NaN  현인숙  01023300219
521  2018방과후강사  NaN  김미경  01055447298
522  2018방과후강사  NaN  정아영  01092218610

방과후프로그램:75
          그룹       학년        이름           전화
575  방과후프로그램  2분기 컴퓨터   1-1 박태환  01092048373
576  방과후프로그램  2분기 컴퓨터   1-1 백승윤  01024752800
577  방과후프로그램  2분기 컴퓨터   1-1 이가연  01088972609
578  방과후프로그램  2분기 컴퓨터   1-1 이선준  01053190106
579  방과후프로그램  2분기 컴퓨터   1-2 김현지  01032965251
580  방과후프로그램  2분기 컴퓨터  1-2 이  찬  01063932379
581  방과후프로그램  2분기 컴퓨터   1-2 이효준  01050421078
582  방과후프로그램  2분기 컴퓨터   1-3 김용민  01086041324
583  방과후프로그램  2분기 컴퓨터   1-3 유채하  01036058699
584  방과후프로그램  2분기 컴퓨터   1-3 전시환  01090074526
585  방과후프로그램  2분기 컴퓨터   1-3 조규빈  01090671703
586  방과후프로그램  2분기 컴퓨터   1-3 최승현  01027535089
587  방과후프로그램  2분기 컴퓨터   2-1 배진원  01072837282
588  방과후프로그램  2분기 컴퓨터   2-2 국중현  01037109872
589  방과후프로그램  2분기 컴퓨터   2-2 양예서  01091272447
590  방과후프로그램  2분기 컴퓨터   2-2 유한결  01054461140
591  방과후프로그램  2분기 컴퓨터   2-3 오상훈  01090801400
592  방과후프로그램  2분기 컴퓨터   5-1 금준호  01051741260
593  방과후프로그램  2분기 컴퓨터   5-1 전성원  01091455760
594  방과후프로그램  2분기 컴퓨터   5-1 전형찬  01031247071
595  방과후프로그램  2분기 컴퓨터   5-1 김나은  01023096289
596  방과후프로그램  2분기 컴퓨터   5-1 박임윤  01032061553
597  방과후프로그램  2분기 컴퓨터   5-1 이소현  01088622315
598  방과후프로그램  2분기 컴퓨터   5-2 송건우  01041186394
599  방과후프로그램  2분기 컴퓨터   5-2 유민준  01054454498
600  방과후프로그램  2분기 컴퓨터   5-2 강민아  01027742347
601  방과후프로그램  2분기 컴퓨터   5-2 김주원  01085513370
602  방과후프로그램  2분기 컴퓨터   5-2 서송연  01062345785
603  방과후프로그램  2분기 컴퓨터   5-2 유미래  01027315197
604  방과후프로그램  2분기 컴퓨터   5-2 황효린  01042587745
..       ...      ...       ...          ...
620  방과후프로그램  2분기 컴퓨터   4-1 안태경  01092237962
621  방과후프로그램  2분기 컴퓨터   4-2 오태강  01047440342
622  방과후프로그램  2분기 컴퓨터   4-2 임채준  01056853523
623  방과후프로그램  2분기 컴퓨터   4-2 허승범  01096763461
624  방과후프로그램  2분기 컴퓨터   4-3 김강현  01048441999
625  방과후프로그램  2분기 컴퓨터   4-3 전형규  01031247071
626  방과후프로그램  2분기 컴퓨터   4-3 최재형  01041395839
627  방과후프로그램  2분기 컴퓨터   3-1 박시영  01090646647
628  방과후프로그램  2분기 컴퓨터   3-1 이성현  01050514682
629  방과후프로그램  2분기 컴퓨터  3-1 우  민  01090451570
630  방과후프로그램  2분기 컴퓨터   3-1 이지안  01044775077
631  방과후프로그램  2분기 컴퓨터   3-2 김예다  01033285511
632  방과후프로그램  2분기 컴퓨터   3-2 김예빈  01066056949
633  방과후프로그램  2분기 컴퓨터   3-2 김현아  01071122558
634  방과후프로그램  2분기 컴퓨터   3-2 김예슬  01066056949
635  방과후프로그램  2분기 컴퓨터   3-2 윤지은  01095801983
636  방과후프로그램  2분기 컴퓨터   3-3 김대윤  01033486015
637  방과후프로그램  2분기 컴퓨터   3-3 김재훈  01088218990
638  방과후프로그램  2분기 컴퓨터   3-3 정승호  01089218572
639  방과후프로그램  2분기 컴퓨터   4-1 박세윤  01086177035
640  방과후프로그램  2분기 컴퓨터   4-1 안예서  01029350455
641  방과후프로그램  2분기 컴퓨터   4-2 김민찬  01037421632
642  방과후프로그램  2분기 컴퓨터   4-2 진우림  01087216605
643  방과후프로그램  2분기 컴퓨터   4-2 김성경  01090422268
644  방과후프로그램  2분기 컴퓨터  4-2 우  현  01090451570
645  방과후프로그램  2분기 컴퓨터   4-2 이신영  01059202837
646  방과후프로그램  2분기 컴퓨터   4-3 고종학  01071082364
647  방과후프로그램  2분기 컴퓨터   4-3 신은혜  01024143320
648  방과후프로그램  2분기 컴퓨터   4-3 이다현  01042962174
649  방과후프로그램  2분기 컴퓨터   4-3 임현정  01033178117

[75 rows x 4 columns]

전시회:21
      그룹   학년       이름           전화
676  전시회  NaN      남윤건  01049199279
677  전시회  NaN      정다은  01024418520
678  전시회  NaN      박희재  01040174132
679  전시회  NaN      이다현  01024612174
680  전시회  NaN      유한결  01054461140
681  전시회  NaN      박희서  01040174132
682  전시회  NaN      김범진  01088060423
683  전시회  NaN      김민주  01088060423
684  전시회  NaN      이소율  01054920703
685  전시회  NaN      김서현  01091386890
686  전시회  NaN      박준우  01067962208
687  전시회  NaN      박준서  01067502208
688  전시회  NaN      이주현  01082465533
689  전시회  NaN      최경화  01064448255
690  전시회  NaN      김민서  01037296774
691  전시회  NaN      이시우  01051780427
692  전시회  NaN      신현진  01059126166
693  전시회  NaN      서연우  01095935411
694  전시회  NaN      정유비  01083982050
695  전시회  NaN  2-1-조민상  01053969041
696  전시회  NaN  5-2-김민주  01088060423

## 미션 1 - 이름에 맞게 전화번호 및 데이터 가져오기

In [36]:
# 데이터를 채울 파일 불러오기
outFile = 'pandas_geni.csv'

### 데이터 프레임 만들기

dfGeni = pd.read_csv(outFile, index_col=0)
dfGeni = dfGeni.loc[1:6]

### 컬럼 명 재 정의 하기

In [73]:
col = ['학년반','성명','희망영재교육기관','전화','비고']
dfGeni.reindex(columns=col)

     학년반   성명 희망영재교육기관  전화     비고
구분
1   31.0  왕지후  안산교육지원청 NaN  안산진흥초
2   31.0  채준서    안산진흥초 NaN    NaN
3   32.0   이원  안산교육지원청 NaN    NaN
4   42.0  박희재  안산교육지원청 NaN    NaN
5   43.0  이다현  안산교육지원청 NaN    NaN
6   61.0  오석준    안산동산고 NaN    NaN

### 데이터 채우기 - 머지 기능 사용

In [74]:
dfGeni = pd.merge(dfMother, dfGeni, left_on='이름', right_on='성명')
dfGeni

         그룹   학년   이름           전화   학년반   성명 희망영재교육기관     비고
0  2018 학부모  3학년  왕지후  01024052201  31.0  왕지후  안산교육지원청  안산진흥초
1  2018 학부모  3학년  채준서  01062610726  31.0  채준서    안산진흥초    NaN
2  2018 학부모  3학년   이원  01032144455  32.0   이원  안산교육지원청    NaN
3  2018 학부모  4학년  박희재  01040174132  42.0  박희재  안산교육지원청    NaN
4  2018 학부모  4학년  이다현  01042962174  43.0  이다현  안산교육지원청    NaN
5  2018 학부모  6학년  오석준  01085798184  61.0  오석준    안산동산고    NaN

### 데이터 프레임 정리하기

In [79]:
dfGeni.drop(dfGeni.columns[[0,5]], axis=1, inplace=True) #불필요한 행 삭제하기, 바로 반영하기
dfGeni

    학년   이름           전화   학년반 희망영재교육기관     비고
0  3학년  왕지후  01024052201  31.0  안산교육지원청  안산진흥초
1  3학년  채준서  01062610726  31.0    안산진흥초    NaN
2  3학년   이원  01032144455  32.0  안산교육지원청    NaN
3  4학년  박희재  01040174132  42.0  안산교육지원청    NaN
4  4학년  이다현  01042962174  43.0  안산교육지원청    NaN
5  6학년  오석준  01085798184  61.0    안산동산고    NaN

In [81]:
dfGeni.to_excel('pandas_GeniPhone.xlsx')