In [1]:
# 판다스 임포트 #pandas
import pandas as pd
from pandas import Series, DataFrame
import re

In [2]:
# path 내의 절대 경로 가져오기 함수 #pandas #느낀점 참고만 하기 
#glob 기능이 더 좋음.
import os

def allfiles(path):
    res = []

    for root, dirs, files in os.walk(path):
        rootpath = os.path.join(os.path.abspath(path), root)

        for file in files:
            filepath = os.path.join(rootpath, file)
            res.append(filepath)

    return res

In [76]:
#하위폴더 파일 부르기
inputFile = './ineu_csv_181003/pandas_ineuMac.csv'

## csv파일 정리하기

In [78]:
df = pd.read_csv(inputFile )

#기수, 직위, 성명, 성별, 전화번호, 비고 가져오기
df.columns = ['num', 'gradYear','rank','name','phone','sex','ifMoney','ifAttend','memo']

# 불필요한 열 삭제하기
df = df.drop(['ifMoney', 'ifAttend'], axis = 1)

# 연락처 빈칸인 행 삭제 #pandas #느낀점
dfSel = df.dropna(thresh=6)

#소속 추가하기
dfSel['school'] = ''

dfSel

/Users/mac/.virtualenvs/studyPython from 2018/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

    num      gradYear  rank  name phone            sex        memo school
3    연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
4     1      2002년 졸업    교사   진선미     여  010-6290-5288         NaN
5     2      2014년 졸업    교사   채정윤     여            NaN         분회장
8     5           34기    교사   이주환     남  010-9481-1589         NaN
28   연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
29    1            14    교장   이선교     남  010-5380-0985         NaN
30    2            20    교감   박문자     여  010-3324-6443         NaN
31    3            39    교사   이진욱     남  010-8856-7633         분회장
32    4          2015    교사   강빛나     여  010-9947-2749         NaN
33    5          2009    교사   구지혜     여  010-9115-0904         NaN
36    8          2009    교사   김장규     남  010-7119-1981         NaN
39   11          2007    교사   유송희     여  010-9230-1121         NaN
42   14          2005    교사   장효규     남  010-2797-1911         NaN
45   17          2013    교사   허지연     여  010-3139-6459         NaN
56   연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
57    1            23    교사   안선옥     여  010-3667-0560         분회장
58    2            30    교사   이경민     여  010-2255-5648         NaN
60    3          2000    교사   권혜은     여  010-4576-2871         NaN
61    4            33    교사   임효진     여  010-7171-3741         NaN
62    5          2007    교사   양형근     남  010-3949-0706         NaN
63    6          2014    교사   김윤희     여  010-2764-4025         NaN
64    7          2012    교사   윤선영     여  010-8938-0328         NaN
65    8          2011    교사   이용호     남  010-2848-9881         NaN
66    9          2010    교사   원지성     남  010-9575-9903         NaN
82   연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
83    1           18기    교사   백서영     여  010-8426-7828         NaN
84    2           24기    교사   이연이     여  010-3340-3789         NaN
85    3           27기    교사   최은주     여  010-3380-3710         NaN
86    4           37기    교사   김태욱     남  010-2241-3849         분회장
87    5           52기    교사   박상은     여  010-9958-5850         NaN
..   ..           ...   ...   ...   ...            ...         ...    ...
834   9         00년졸업    교사   조성숙     여  010-3215-6418         NaN
850  연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
851   1      2012.02.    교사   유혜영     여  010-9559-3467         NaN
852   2      2015.02.    교사   오민주     여  010-7676-0855         NaN
853   3      2007.02.    교사   이승우     남  010-4916-9741         NaN
854   4      2004.02.    교사   김수경     여  010-8634-6335         NaN
855   5      2011.02.    교사   박상원     남  010-4640-0864         분회장
875  연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
876   1           27회    교감   김선경     여  010-8889-0466         NaN
877   2           34회    교사   안준우     남  010-8298-9165         분회장
878   3           20회    교사   김은미     여  010-3338-3229         NaN
879   4           49회    교사   장용석     남  010-2553-3216         NaN
880   5           23기  수석교사   권영석     남  010-2008-3449         NaN
900  연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
901   1           17회    교장   조병훈     남  010-4310-0195         NaN
902   2           24회    교감   박성실     여  010-6365-9295         NaN
903   3           32회    교사   심봉섭     남  010-3389-5466         분회장
904   4           35회    교사   최정석     남  010-8948-5127         NaN
905   5           39회    교사   이유선     여  010-8982-0927         NaN
906   6           41회    교사   이효주     여  010-8578-6483         NaN
907   7           42회    교사   배대웅     남  010-3560-8150         NaN
908   8           45회    교사   김민정     여  010-5131-9319         NaN
909   9           48회    교사   장혜진     여  010-9425-2112         NaN
910  10           49회    교사   이윤지     여  010-2020-5843         NaN
911  11           50회    교사   서지희     여  010-3465-1410         NaN
925  연번  기수 (또는 졸업년도)     직    성명    성별     연락처 (전화번호)  비고 (분회장 등)
926   1            37   장학사   김현식     남  010-5497-7912         분회장
927   2            30   장학사   이원주     여  010-5765-8860         NaN
928   3            32   장학사  정  미     여  010-3143-9812         NaN
929   4            35   장학사   이대오     남  010-4496-3912         NaN

[277 rows x 8 columns]

In [79]:
dfEdit = dfSel

In [94]:
# 조건을 검색하여 특정행 삭제하기 
# 조건에 맞는 행을 검색 → 인덱스를 따서 데이터 프레임에서 삭제
dfDel = dfEdit.loc[(dfEdit['num'].str.contains('연번'))]
dfEdit.drop(dfDel.index, inplace=True)

/Users/mac/.virtualenvs/studyPython from 2018/lib/python3.6/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [136]:
# 직위로 정렬후 인덱싱 다시 하기
dfEdit=dfEdit.sort_values(by = ['rank', 'name'])
dfEdit.reset_index(drop=True, inplace=True)
dfEdit.head()

  gradYear rank name phone            sex memo school
0      27회   교감  김선경     여  010-8889-0466  NaN
1      30회   교감  목진식     남  010-3358-4996  NaN
2       24   교감  민명애     여  010-6282-2351  NaN
3       18   교감  박노빈     남  010-5260-0549  NaN
4       20   교감  박문자     여  010-3324-6443  NaN

In [107]:
# num컬럼 행 삭제하기 #pandas
dfEdit.drop('num',axis=1, inplace=True)

## Groupby 기능 활용하기

In [137]:
# 직위로 묶어서 변수에 넣기
groupbyRank = dfEdit.groupby('rank')

In [138]:
# 그룹을 개괄적으로 확인하기
groupbyRank.groups

{'교감': Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int64'),
 '교사': Int64Index([ 14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
             ...
             210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
            dtype='int64', length=206),
 '교장': Int64Index([220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
             233],
            dtype='int64'),
 '수석교사': Int64Index([234], dtype='int64'),
 '장학사': Int64Index([235, 236, 237, 238], dtype='int64')}

In [140]:
# 반복문을 이용하여 그룹을 출력하기 #pandas #느낀점 
for name, group in groupbyRank:
    print(name + " : " + str(len(group)))
    print(group)
    print()

교감 : 14
   gradYear rank name phone            sex memo school
0       27회   교감  김선경     여  010-8889-0466  NaN
1       30회   교감  목진식     남  010-3358-4996  NaN
2        24   교감  민명애     여  010-6282-2351  NaN
3        18   교감  박노빈     남  010-5260-0549  NaN
4        20   교감  박문자     여  010-3324-6443  NaN
5       24회   교감  박성실     여  010-6365-9295  NaN
6       29기   교감  박진서     남  010-9132-3469  NaN
7        24   교감  송인식     남  010-3298-5624  NaN
8        23   교감  안상규     남  010-2032-9847  NaN
9        23   교감  원영효     남  010-5560-5692  NaN
10      20회   교감  윤현미     여  010-3273-2627  NaN
11      20회   교감  윤현미     여  010-3273-2627  NaN
12     1994   교감  장재성     남  010-6246-2342  NaN
13       30   교감  최은희     여  010-5357-8043  NaN

교사 : 206
     gradYear rank name phone            sex memo school
14         47   교사  강남우     남  010.4009.4907  NaN
15         35   교사  강무진     남  010-2750-7765  NaN
16       2015   교사  강빛나     여  010-9947-2749  NaN
17        비공개   교사  강성구     남            비공개  NaN
18         34   교사  강세훈     남  010-7637-8737  NaN
19         51   교사  강수민     여  010-8585-2704  NaN
20         50   교사  강혜미     여  010-9083-6329  NaN
21        30기   교사  강홍주     남  010-2478-7260  NaN
22       2001   교사  강효주     여  010-2401-0958  NaN
23         49   교사  고봄이     여  010-2460-5246  NaN
24   2006 41기   교사  고성은     남  010-7737-5794  NaN
25         44   교사  고영윤     남  010-8526-9330  NaN
26       2005   교사  고정욱     남  010-5086-4497  분회장
27       1997   교사  고혜숙     여  010-8256-3081  NaN
28       2009   교사  구지혜     여  010-9115-0904  NaN
29        50회   교사  권유경     여  010-9561-0420
30      93 학번   교사  권혁숙     여  010-9329-7260  NaN
31       2000   교사  권혜은     여  010-4576-2871  NaN
32       2010   교사  김두영     남  010-6650-0383  NaN
33       2004   교사  김미희     여  010-7122-4427  NaN
34         44   교사  김민국     남  010-4402-0502  NaN
35        45회   교사  김민정     여  010-5131-9319  NaN
36        39회   교사  김선중     남  010-8881-4156  분회장
37        46기   교사   김설     여  010-9847-0219  NaN
38         39   교사  김성곤     남  010-8940-9258  분회장
39         47   교사  김성재     남  010-9177-5238  분회장
40        비공개   교사  김성진     남            비공개  NaN
41         49   교사  김성해     여  010-5064-9193  NaN
42         31   교사  김세영     남  010-3733-9516  분회장
43         21   교사  김소현     여  010-2370-0463  NaN
..        ...  ...  ...   ...            ...  ...    ...
190        45   교사  정한길     남  010-8665-4810  분회장
191        42   교사  조보라     여            비공개  NaN
192     00년졸업   교사  조성숙     여  010-3215-6418  NaN
193      2008   교사  조양희     여  010-4154-2346  NaN
194        44   교사  조인석     남  010-9596-4741  NaN
195  2002년 졸업   교사  진선미     여  010-6290-5288  NaN
196  2002년 졸업   교사  진선미     여  010-6290-5288  NaN
197      2010   교사  진성언     남  010-9580-1830  NaN
198       21회   교사  진소현     여  010 2391 9185  NaN
199      2001   교사  채달석     남  010-3309-1659  분회장
200  2014년 졸업   교사  채정윤     여            NaN  분회장
201  2014년 졸업   교사  채정윤     여            NaN  분회장
202      2009   교사  최경아     여  010-2065-7814    .
203      2013   교사   최민     여  010-7566-9797  NaN
204      2013   교사  최보배     여  010-3542-6901  NaN
205      2011   교사  최소영     여  010-3074-5174  NaN
206       42회   교사  최유미     여  010-2784-5425
207       27기   교사  최은주     여  010-3380-3710  NaN
208       27기   교사  최은주     여  010-3380-3710  NaN
209       35회   교사  최정석     남  010-8948-5127  NaN
210      2010   교사  최준석     남  010-5652-5696  NaN
211      2014   교사  탁예원     여  010-3543-5225  분회장
212      2014   교사  한지혜     여              -  NaN
213        32   교사  한진영     여  010-4926-8353  NaN
214      2013   교사  허지연     여  010-3139-6459  NaN
215       비공개   교사  홍명희     여            비공개  NaN
216        36   교사  홍정주     여  010-8246-3693  NaN
217       39회   교사  홍지현     여  010-9921-8279
218       42기   교사  황정환     남  010-4347-8587  분회장
219        28   교사  황현연     남  010-7664-8910  NaN

[206 rows x 7 columns]

교장 : 14
    gradYear rank name phone            sex memo school
220       24   교장  김국남     남  010-6390-6466  NaN
221     1989   교장  김동목     남  010-6264-7081  NaN
222      18회   교장  김현숙     여  010-8787-5521  NaN
223       18   교장  백재선     여  010-9267-6967  NaN
224       18   교장  성영경     남  010-4318-8883  NaN
225       14   교장  이선교     남  010-5380-0985  NaN
226       22   교장  이재평     남  010-8592-0419  NaN
227     1978   교장  임영택     남  010-6301-6718  NaN
228       20   교장  임정일     남  010-3630-2432  NaN
229      17회   교장  조병훈     남  010-4310-0195  NaN
230       24   교장  조주은     여  010.9414.7081  부회장
231     1981   교장  천옥희     남  010-8281-6909  NaN
232      16회   교장  한명희     여  010-4207-9235  NaN
233       17   교장  황병희     남  010-9150-5653  NaN

수석교사 : 1
    gradYear  rank name phone            sex memo school
234      23기  수석교사  권영석     남  010-2008-3449  NaN

장학사 : 4
    gradYear rank  name phone            sex memo school
235       37  장학사   김현식     남  010-5497-7912  분회장
236       35  장학사   이대오     남  010-4496-3912  NaN
237       30  장학사   이원주     여  010-5765-8860  NaN
238       32  장학사  정  미     여  010-3143-9812  NaN

In [154]:
# 행에서 특정 조건에 맞는 문자열 검색하기 #느낀점 #pandas
dfTeacher = dfEdit.loc[(dfEdit['rank'].str.contains('교사'))]
dfTeacher.head()

   gradYear rank name phone            sex memo school
14       47   교사  강남우     남  010.4009.4907  NaN
15       35   교사  강무진     남  010-2750-7765  NaN
16     2015   교사  강빛나     여  010-9947-2749  NaN
17      비공개   교사  강성구     남            비공개  NaN
18       34   교사  강세훈     남  010-7637-8737  NaN

In [155]:
# 행에서 특정 조건에 맞는 문자열 검색하기 #느낀점 #pandas
dfSubPrinciple = dfEdit.loc[(dfEdit['rank'].str.contains('교감'))]
dfSubPrinciple.head()

  gradYear rank name phone            sex memo school
0      27회   교감  김선경     여  010-8889-0466  NaN
1      30회   교감  목진식     남  010-3358-4996  NaN
2       24   교감  민명애     여  010-6282-2351  NaN
3       18   교감  박노빈     남  010-5260-0549  NaN
4       20   교감  박문자     여  010-3324-6443  NaN

In [156]:
# 행에서 특정 조건에 맞는 문자열 검색하기 #느낀점 #pandas
dfPrinciple = dfEdit.loc[(dfEdit['rank'].str.contains('교장'))]
dfPrinciple.head()

    gradYear rank name phone            sex memo school
220       24   교장  김국남     남  010-6390-6466  NaN
221     1989   교장  김동목     남  010-6264-7081  NaN
222      18회   교장  김현숙     여  010-8787-5521  NaN
223       18   교장  백재선     여  010-9267-6967  NaN
224       18   교장  성영경     남  010-4318-8883  NaN

In [157]:
dfTeacher.to_csv('pandas_ineu_teacher_181014.csv')

In [158]:
dfSubPrinciple.to_csv('pandas_ineu_subPrinciple_181014.csv')

In [159]:
dfPrinciple.to_csv('pandas_ineu_principle_181014.csv')

In [160]:
dfEdit.to_csv('pandas_ineu_All_181014.csv')

## 파일 정리 반복문 만들기

In [59]:
#정규표현식 적용하기
inputFiles = allfiles('./ineu_csv_181003/')
p = re.compile(r'\((.*)\)')     #괄호 안의 내용 뽑아내기 검색식 괄호 2개이용하는 것과 괄호 앞에 역슬래시를 넣는 것이 포인트 #느낀점 #표현식
schoolName = []
for inputFile in inputFiles:
#     print(inputFile)
    i = p.findall(inputFile)
    schoolName.append(i)
    
schoolName

[[],
 ['경일초'],
 ['고잔초'],
 ['능길초'],
 ['대동초'],
 ['대부초'],
 ['덕인초'],
 ['반월초'],
 ['별망초'],
 ['본오초'],
 ['상록초'],
 ['석호초'],
 ['선부초'],
 ['선일초'],
 ['성안초'],
 ['성포초'],
 ['송호초'],
 ['시랑초'],
 ['신길초'],
 ['안산교육지원청'],
 ['안산부곡초'],
 ['안산서초'],
 ['안산석수초'],
 ['안산양지초'],
 ['안산원곡초'],
 ['안산중앙초'],
 ['안산진흥초'],
 ['안산창촌초'],
 ['안산청석초'],
 ['안산초'],
 ['안산해양초'],
 ['안산호원초'],
 ['원일초'],
 ['정재초'],
 ['초당초'],
 ['초지초'],
 ['팔곡초'],
 ['학현초'],
 ['호동초'],
 ['9.1일자']]

In [139]:
# 인덱스 값을 이용하여 내용 수정하기
listIndex = [213, 214, 215, 216, 217, 218, 219]
for i in listIndex:
    dfEdit.iloc[i]['rank'] = '교사'

In [70]:
#정규표현식 적용하기
import glob

p = re.compile(r'\((.*)\)')     #괄호 안의 내용 뽑아내기 검색식 괄호 2개이용하는 것과 괄호 앞에 역슬래시를 넣는 것이 포인트 #느낀점 #표현식
schoolName = []
for inputFile in glob.glob('ineu_csv_181003/2018*.csv', recursive=True):
    print(inputFile)
    i = p.findall(inputFile)
    print(i)
    schoolName.append(i)
    
schoolName

ineu_csv_181003/2018학년도 경인교대 동문회원 명부(경일초).csv
['경일초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(고잔초).csv
['고잔초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(능길초).csv
['능길초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대동초).csv
['대동초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대부초).csv
['대부초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(덕인초).csv
['덕인초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(반월초).csv
['반월초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(별망초).csv
['별망초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(본오초).csv
['본오초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(상록초).csv
['상록초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(석호초).csv
['석호초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선부초).csv
['선부초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선일초).csv
['선일초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성안초).csv
['성안초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성포초).csv
['성포초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(송호초).csv
['송호초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(시랑초).csv
['시랑초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(신길초).csv
['신길초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산교육지원청).csv
['안산교육지원청']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산부곡초).csv
['안산부곡초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산서초).csv
['안산서초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산석수초).csv
['안산석수초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산양지초).csv
['안산양지초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산원곡초).csv
['안산원곡초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산중앙초).csv
['안산중앙초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산진흥초).csv
['안산진흥초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산창촌초).csv
['안산창촌초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산청석초).csv
['안산청석초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산초).csv
['안산초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산해양초).csv
['안산해양초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산호원초).csv
['안산호원초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(원일초).csv
['원일초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(정재초).csv
['정재초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초당초).csv
['초당초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초지초).csv
['초지초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(팔곡초).csv
['팔곡초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(학현초).csv
['학현초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(호동초).csv
['호동초']

[['경일초'],
 ['고잔초'],
 ['능길초'],
 ['대동초'],
 ['대부초'],
 ['덕인초'],
 ['반월초'],
 ['별망초'],
 ['본오초'],
 ['상록초'],
 ['석호초'],
 ['선부초'],
 ['선일초'],
 ['성안초'],
 ['성포초'],
 ['송호초'],
 ['시랑초'],
 ['신길초'],
 ['안산교육지원청'],
 ['안산부곡초'],
 ['안산서초'],
 ['안산석수초'],
 ['안산양지초'],
 ['안산원곡초'],
 ['안산중앙초'],
 ['안산진흥초'],
 ['안산창촌초'],
 ['안산청석초'],
 ['안산초'],
 ['안산해양초'],
 ['안산호원초'],
 ['원일초'],
 ['정재초'],
 ['초당초'],
 ['초지초'],
 ['팔곡초'],
 ['학현초'],
 ['호동초']]

In [70]:
#정규표현식 적용하기
import glob

p = re.compile(r'\((.*)\)')     #괄호 안의 내용 뽑아내기 검색식 괄호 2개이용하는 것과 괄호 앞에 역슬래시를 넣는 것이 포인트 #느낀점 #표현식
schoolName = []
for inputFile in glob.glob('ineu_csv_181003/2018*.csv', recursive=True):
     df 
    print(inputFile)
    i = p.findall(inputFile)
    print(i)
    schoolName.append(i)
    
schoolName

ineu_csv_181003/2018학년도 경인교대 동문회원 명부(경일초).csv
['경일초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(고잔초).csv
['고잔초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(능길초).csv
['능길초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대동초).csv
['대동초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대부초).csv
['대부초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(덕인초).csv
['덕인초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(반월초).csv
['반월초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(별망초).csv
['별망초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(본오초).csv
['본오초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(상록초).csv
['상록초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(석호초).csv
['석호초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선부초).csv
['선부초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선일초).csv
['선일초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성안초).csv
['성안초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성포초).csv
['성포초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(송호초).csv
['송호초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(시랑초).csv
['시랑초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(신길초).csv
['신길초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산교육지원청).csv
['안산교육지원청']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산부곡초).csv
['안산부곡초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산서초).csv
['안산서초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산석수초).csv
['안산석수초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산양지초).csv
['안산양지초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산원곡초).csv
['안산원곡초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산중앙초).csv
['안산중앙초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산진흥초).csv
['안산진흥초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산창촌초).csv
['안산창촌초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산청석초).csv
['안산청석초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산초).csv
['안산초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산해양초).csv
['안산해양초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산호원초).csv
['안산호원초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(원일초).csv
['원일초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(정재초).csv
['정재초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초당초).csv
['초당초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초지초).csv
['초지초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(팔곡초).csv
['팔곡초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(학현초).csv
['학현초']
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(호동초).csv
['호동초']

[['경일초'],
 ['고잔초'],
 ['능길초'],
 ['대동초'],
 ['대부초'],
 ['덕인초'],
 ['반월초'],
 ['별망초'],
 ['본오초'],
 ['상록초'],
 ['석호초'],
 ['선부초'],
 ['선일초'],
 ['성안초'],
 ['성포초'],
 ['송호초'],
 ['시랑초'],
 ['신길초'],
 ['안산교육지원청'],
 ['안산부곡초'],
 ['안산서초'],
 ['안산석수초'],
 ['안산양지초'],
 ['안산원곡초'],
 ['안산중앙초'],
 ['안산진흥초'],
 ['안산창촌초'],
 ['안산청석초'],
 ['안산초'],
 ['안산해양초'],
 ['안산호원초'],
 ['원일초'],
 ['정재초'],
 ['초당초'],
 ['초지초'],
 ['팔곡초'],
 ['학현초'],
 ['호동초']]

In [ ]:
# 파일명에서 '**초' 찾아내기
p = re.compile('\w*초')
t = '/Volumes/SeconBay/Gdrive/★작업중/SW_PyCharm/studyPython from 2018/openpyXl/ineu_csv_181003/./ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산정지초).csv'
i = p.findall(t)
i

## 폴더 및 파일 읽어오기 참고 자료

In [49]:
#현재 폴더의 파일과 하위 폴더 파일명가져오기
import os
for root, dirs, files in os.walk('./'): #root, diirs, files형태의 튜플을 읽기
    for file in files:
        print(file)

#180802 xls_getCells.py
#180802 xls_getCells_projet.py
#180802 xls_getSheet.py
#180802 xls_open.py
#180805 xls_getRow.py
#180805 xls_priceUpdate_algo.py
#180805 xls_priceUpdate_algo_coding.py
#180806 census_algo.py
#180806 census_algo_coding.py
#180806 produceSale_algo.py
#180806 produceSale_algo_coding.py
#180808 #project csv_removeHeader_algo.py
#180808 #project csv_removeHeader_algo_coding.py
#180808 #project joson_quickWeather_algo.py
1.csv
2018_관내전보내신취합용(학교용)_20180907 - 한셀용.xls
2018_전보취합용(교육지원청용)_20180907.xls
2018학년도 경인교대 동문회원 명부(경일초).csv
census.py
census.xlsx
example.xlsx
excelMerge01.xlsx
excelMerge02.xlsx
insa01.xls
lawFather.csv
lawFather.gsheet
lawFatherSeokSms.csv
lawFatherSeokSms.xlsx
openpyXl_excelMergeFile_180915.py
openpyXl_excelMergeFile_allFileOpen_180915.py
openpyXl_excelMergeFile_allFileOpen__temp_180915.py
openpyXl_insaAntaewoo_180915.py
openpyXl_workout_180915.py
openpyXl_workout_180915_temp.py
pandas_contacts.csv
pandas_googleAddress.csv
pandas_googleAddress_181012.csv
pandas_googleAddress_181012.xlsx
pandas_googlePhoneAddress_181011.ipynb
pandas_googlePhoneAddress_Pycharm_181011.ipynb
pandas_googlePhoneAddress_Pycharm_181011.py
pandas_ineuCsvCollect_181013.ipynb
pandas_lawFather_seokAll (1).gsheet
pandas_lawFather_seokAll.csv
pandas_lawFather_seokAll.gsheet
pandas_lawFatherMoney_181008.ipynb
pandas_lawFatherMoneyPycharm_181008.ipynb
pandas_lawFatherMoneyPycharm_181008.py
pandas_lawFile_181008.csv
pandas_makeSmsAddressByMachingAll_181012.ipynb
pandas_makeSmsAddressByMachingAllApplyLambda_181013.ipynb
pandas_matchSms.csv
pandas_phoneAddress_191011.py
pandas_readClipboard_181013.ipynb
pandas_resultSmsMatch.csv
pandas_resultSmsMatch.gsheet
produceSales.py
produceSales.xlsx
pyXl_insaAntaewoo_180914.py
result_excelMergeAll_temp.xlsx
result_insaAntaewoo.xlsx
test.ipynb
test.xlsx
updateProductSales.xlsx
workOut.xlsx
능길초_나교사_관내전보_(18_09_14).xls
붙임1)2018_관내전보내신서(개인용)-20180903(최종).xlsm
안산양지초_가교사_관내전보_(18_09_18).xls
안산양지초_나교사.xls
안산양지초_나교사.xlsx
안산양지초_라교사_관내전보_(18_09_18).xls
안산양지초_마교사_관내전보_(18_09_18).xls
pandas_googlePhoneAddress_181011-checkpoint.ipynb
pandas_googlePhoneAddress_Pycharm_181011-checkpoint.ipynb
pandas_ineuCsvCollect_181013-checkpoint.ipynb
pandas_lawFatherMoney_181008-checkpoint.ipynb
pandas_lawFatherMoneyPycharm_181008-checkpoint.ipynb
pandas_makeSmsAddressByMachingAll_181012-checkpoint.ipynb
pandas_makeSmsAddressByMachingAllApplyLambda_181013-checkpoint.ipynb
pandas_readClipboard_181013-checkpoint.ipynb
test-checkpoint.ipynb
2018학년도 경인교대 동문회원 명부(경일초).csv
2018학년도 경인교대 동문회원 명부(고잔초).csv
2018학년도 경인교대 동문회원 명부(능길초).csv
2018학년도 경인교대 동문회원 명부(대동초).csv
2018학년도 경인교대 동문회원 명부(대부초).csv
2018학년도 경인교대 동문회원 명부(덕인초).csv
2018학년도 경인교대 동문회원 명부(반월초).csv
2018학년도 경인교대 동문회원 명부(별망초).csv
2018학년도 경인교대 동문회원 명부(본오초).csv
2018학년도 경인교대 동문회원 명부(상록초).csv
2018학년도 경인교대 동문회원 명부(석호초).csv
2018학년도 경인교대 동문회원 명부(선부초).csv
2018학년도 경인교대 동문회원 명부(선일초).csv
2018학년도 경인교대 동문회원 명부(성안초).csv
2018학년도 경인교대 동문회원 명부(성포초).csv
2018학년도 경인교대 동문회원 명부(송호초).csv
2018학년도 경인교대 동문회원 명부(시랑초).csv
2018학년도 경인교대 동문회원 명부(신길초).csv
2018학년도 경인교대 동문회원 명부(안산교육지원청).csv
2018학년도 경인교대 동문회원 명부(안산부곡초).csv
2018학년도 경인교대 동문회원 명부(안산서초).csv
2018학년도 경인교대 동문회원 명부(안산석수초).csv
2018학년도 경인교대 동문회원 명부(안산양지초).csv
2018학년도 경인교대 동문회원 명부(안산원곡초).csv
2018학년도 경인교대 동문회원 명부(안산중앙초).csv
2018학년도 경인교대 동문회원 명부(안산진흥초).csv
2018학년도 경인교대 동문회원 명부(안산창촌초).csv
2018학년도 경인교대 동문회원 명부(안산청석초).csv
2018학년도 경인교대 동문회원 명부(안산초).csv
2018학년도 경인교대 동문회원 명부(안산해양초).csv
2018학년도 경인교대 동문회원 명부(안산호원초).csv
2018학년도 경인교대 동문회원 명부(원일초).csv
2018학년도 경인교대 동문회원 명부(정재초).csv
2018학년도 경인교대 동문회원 명부(초당초).csv
2018학년도 경인교대 동문회원 명부(초지초).csv
2018학년도 경인교대 동문회원 명부(팔곡초).csv
2018학년도 경인교대 동문회원 명부(학현초).csv
2018학년도 경인교대 동문회원 명부(호동초).csv
안산지원청_인천교대_2018동문관리자명부(9.1일자).csv
data1_2018-09-21.xlsx
data_2018-09-20.xlsx
data_2018-09-21.xlsx
insa01.xls
insa02.xls
insa03.xls
insa04.xls
openpyXl_insaAntaewoo_180915.py
openpyXl_insaAntaewoo_copyCellAttributeHas_190819.py
openpyXl_insaAntaewoo_excludeHeader_180915.py
openpyXl_insaAntaewoo_makeHeader.py
openpyXl_insaAntaewoo_makeHeader_appendData.py
openpyXl_insaAntaewoo_readXlsCopyWriteXlsx_190820.py
out.xlsx
out_2018-09-20.xlsx
result_insaAntaewoo.xlsx
xlsxwriter

In [135]:
p.findall('/Volumes/SeconBay/Gdrive/★작업중/SW_PyCharm/studyPython from 2018/openpyXl/ineu_csv_181003/./ineu_csv_181003/2018학년도 경인교대 동문회원 명부(경일초).csv')

['경일초']

## 파일 관련 작업하기 golb

In [60]:
import glob

In [63]:
# 현재 디렉토리 내에 csv파일명 출력하기
for filename in glob.glob('*.csv'):
    print(filename)

1.csv
2018학년도 경인교대 동문회원 명부(경일초).csv
lawFather.csv
lawFatherSeokSms.csv
pandas_contacts.csv
pandas_googleAddress.csv
pandas_googleAddress_181012.csv
pandas_lawFather_seokAll.csv
pandas_lawFile_181008.csv
pandas_matchSms.csv
pandas_resultSmsMatch.csv

In [67]:
#하위 폴더 내의 csv파일 출력하기
for filename in glob.iglob('ineu_csv_181003/2018*.csv', recursive=True):
    print(filename)

ineu_csv_181003/2018학년도 경인교대 동문회원 명부(경일초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(고잔초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(능길초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대동초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대부초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(덕인초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(반월초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(별망초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(본오초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(상록초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(석호초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선부초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선일초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성안초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성포초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(송호초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(시랑초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(신길초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산교육지원청).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산부곡초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산서초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산석수초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산양지초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산원곡초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산중앙초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산진흥초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산창촌초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산청석초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산해양초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산호원초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(원일초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(정재초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초당초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초지초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(팔곡초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(학현초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(호동초).csv

In [68]:
#현재디렉토리와 하위 폴더의 csv파일 출력하기
for filename in glob.iglob('**/2018*.csv', recursive=True):
    print(filename)

2018학년도 경인교대 동문회원 명부(경일초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(경일초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(고잔초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(능길초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대동초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(대부초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(덕인초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(반월초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(별망초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(본오초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(상록초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(석호초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선부초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(선일초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성안초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(성포초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(송호초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(시랑초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(신길초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산교육지원청).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산부곡초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산서초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산석수초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산양지초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산원곡초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산중앙초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산진흥초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산창촌초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산청석초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산해양초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(안산호원초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(원일초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(정재초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초당초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(초지초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(팔곡초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(학현초).csv
ineu_csv_181003/2018학년도 경인교대 동문회원 명부(호동초).csv

## 해결과제
- csv파일 윈도우에서 읽혀지는지 테스트(데이터 프레임 만들기)
- 읽어지는 경우 데이터 프레임으로 정리후 리스트로 만들기
- 리스트 append하기
- 최종 데이터 프레임 만들기